apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingressclass.yaml
- ingress.yaml

images:
- name: frontend
  newName: 381492057134.dkr.ecr.us-east-1.amazonaws.com/adowol-dev/frontend
  newTag: sha-17f39f351314816f34a9d4799a7d43f30e8e3e91
