apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingressclass.yaml
  - ingress.yaml

images:
  - name: frontend
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/adowol-dev/frontend
    newTag: initial
