apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml

images:
  - name: service-b
    newName: 381492057134.dkr.ecr.us-east-1.amazonaws.com/adowol-dev/service-b
    newTag: initial
